# Disable thymeleaf. We use JSF
spring:
  thymeleaf:
    enabled: false
  mvc:
    view:
      suffix: .xhtml
  application:
    name: elcar
  data:
    mongodb:
      host: localhost
      port: 27017
      database: elcar
      username: elcar
      password: elcar
      authentication-database: admin

